project:
  type: website
  output-dir: docs

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

website:
  title: "Bibhabasu's Blogs"
  site-url: "https://bibhabasumohapatra.github.io/"
  description: "Blog page of Bibhabasu Mohapatra."
  favicon: posts/favicon.ico
  search: false
  twitter-card:
    creator: "@RisingSayak"
    card-style: summary
  open-graph: true
  repo-actions: [edit, issue]
  repo-branch: "master"
  repo-url: "https://github.com/bibhabasumohapatra/bibhabasumohapatra.github.io"
  google-analytics: "UA-163448909-1"
  navbar:
    background: primary
    right:
      - text: "bAcK 2 h0Me"
        href: https://bibhabasu-mohapatra.space
      - icon: twitter
        href: https://x.com/bibhabasuM1610
      - icon: linkedin
        href: https://www.linkedin.com/in/bibhabasu-mohapatra-3b8205193/
      - icon: github
        href: https://github.com/bibhabasumohapatra

execute:
  freeze: auto

resources:
  - CNAME